object Main extends App {
  basics.Main.run()
  functionsandmethods.Main.run()
  controlstructures.Main.run()
  exceptionhandling.Main.run()
  classes.Main.run()
  tuples.Main.run()
  userinput.Main.run()
  enumerations.Main.run()
  shapes.Main.run()
  collections.Main.run()
  optionsomenone.Main.run()
  companionobjects.Main.run()
  caseclasses.Main.run()
  caseobjects.Main.run()
  trysuccessfailure.Main.run()
}